acnep/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from acnep import settings

admin.site.site_header = "Sistema ACNEP Admin"
admin.site.site_title = "Sistema ACNEP Portal"
admin.site.index_title = "Bienvenido al administrador del Sistema ACNEP"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'acnep.views.handler404'
handler500 = 'acnep.views.handler500'

base/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

import chaplains
from chaplains import urls

import pagos
from pagos import urls

from .views import *

urlpatterns = [

    # BASE URLs
    path('login', Login.as_view(), name='login' ),
    path('', DashboardView.as_view(), name='dashboard'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('index', BlankView.as_view(), name='index'),

    # Datatables translation
    path('datatables_translation', DataTablesTranslationsJsonView.as_view(), name='datatables_translation'),

    # APPS URLS
    # Chaplains
    path('chaplains/', include(chaplains.urls)),
    # Payment History, Subscriptions and Plans
    # path('', include(pagos.urls)),
]

pagos/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    # PLAN
    path('plan/list/', PlanDatatableView.as_view(), name='plan_list'),
    path('plan/details/<int:pk>', PlanDetailsView.as_view(), name='plan_details'),
    path('plan/create/', PlanCreateView.as_view(), name='plan_create'),
    path('plan/update/<int:pk>', PlanUpdateView.as_view(), name='plan_update'),
    path('plan/delete/<int:pk>', PlanDeleteView.as_view(), name='plan_delete'),
    # PAYMENT HISTORY
    path('payment_history/list/', PaymentHistoryDatatableView.as_view(), name='payment_history_list'),
    path('payment_history/details/<int:pk>', PaymentHistoryDetailsView.as_view(), name='payment_history_details'),
    path('payment_history/create/', PaymentHistoryCreateView.as_view(), name='payment_history_create'),
    path('payment_history/update/<int:pk>', PaymentHistoryUpdateView.as_view(), name='payment_history_update'),
    path('payment_history/delete/<int:pk>', PaymentHistoryDeleteView.as_view(), name='payment_history_delete'),
    # SUBSCRIPTIONS
    path('subscriptions/list/', SubscriptionDatatableView.as_view(), name='subscriptions_list'),
    path('subscriptions/details/<int:pk>', SubscriptionDetailsView.as_view(), name='subscriptions_details'),
    path('subscriptions/create/', SubscriptionCreateView.as_view(), name='subscriptions_create'),
    path('subscriptions/update/<int:pk>', SubscriptionUpdateView.as_view(), name='subscriptions_update'),
    path('subscriptions/delete/<int:pk>', SubscriptionDeleteView.as_view(), name='subscriptions_delete'),
    path('subscriptions/adetails/', SubscriptionADetailsView.as_view(), name='suscriptions_adetails'),
    # API
    path('api/webhook/', WebHook.as_view(), name='webhook'),
]

pagos/models.py
import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _
from auditlog.registry import auditlog
from softdelete.models import SoftDeleteObject
from base.models import TimeStampModel

# Create your models here.
from chaplains.models import Chaplain


class Plan(SoftDeleteObject, TimeStampModel):
    name = models.CharField(max_length=50,
                            verbose_name=_('Name'),
                            null=False, blank=False)
    description = models.CharField(max_length=100,
                                   verbose_name=_('Description'),
                                   null=False, blank=False)
    monthly_price = models.IntegerField(
        verbose_name=_('Monthly Price'),
        null=False, blank=False
    )
    yearly_price = models.IntegerField(
        verbose_name=_('Monthly Price'),
        null=False, blank=False
    )

    class Meta:
        verbose_name = _('Plan')
        verbose_name_plural = _('Plans')

    def __str__(self):
        return str(self.name)


auditlog.register(Plan)


# SUBSCRIPTIONS
class Subscription(SoftDeleteObject, TimeStampModel):
    chaplain = models.ForeignKey(to=Chaplain, on_delete=models.PROTECT,
                                 verbose_name=_('Chaplain'),
                                 null=False, blank=False,
                                 related_name='subscriptions')
    plan = models.ForeignKey(to=Plan, on_delete=models.PROTECT,
                             verbose_name=_('Plan'),
                             null=False, blank=False,
                             related_name='subscriptions')
    startDate = models.DateField(verbose_name=_('Start Date'),
                             null=False, blank=False,)
    endDate = models.DateField(verbose_name=_('End Date'),
                             null=True, blank=True,)
    finishDate = models.DateField(verbose_name=_('Finish Date'),
                             null=True, blank=True,)
    isActive = models.BooleanField(default=False, null=True, blank=True)
    url = models.URLField(null=True, blank=True)

    class Meta:
        verbose_name = _('Subscription')
        verbose_name_plural = _('Subscriptions')

    def __str__(self):
        return str(self.chaplain.name + ' - ' + str(self.plan.monthly_price))

    def cancelsubscription(self):
        self.isActive = False
        self.finishDate = datetime.datetime.now()
        print("Cancelado correctamente")
        self.save()
        return self


auditlog.register(Subscription)


# PAYMENT HISTORY
class PaymentHistory(SoftDeleteObject, TimeStampModel):
    choices = (
        ('1', 'Efectivo'),
        ('2', 'Billetera Electronica'),
        ('3', 'Transferencia Bancaria'),
        ('4', 'Deposito Bancario'),
        ('5', 'Tarjeta Credito'),
        ('6', 'Tarjeta Debito'),
        ('7', 'AdamsPay'),
    )
    payment_type = models.CharField(max_length=25, choices=choices,
                                    verbose_name=_('Payment Type'),
                                    null=False, blank=False)
    date = models.DateField()
    amount = models.FloatField(verbose_name=_('Amount'), null=False, blank=False)
    ref_number = models.CharField(max_length=30,
                                  verbose_name=_('Reference Number'),
                                  null=False, blank=False)
    subscription = models.ForeignKey(to=Subscription, on_delete=models.PROTECT,
                                     verbose_name=_('Payment History'),
                                     null=True, blank=True,
                                     related_name='payment')


auditlog.register(PaymentHistory)

pagos/views.py
from datatableview.views import DatatableView
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from datatableview import Datatable, columns
from datetime import date, datetime
from django.db import transaction
from django.template import RequestContext, loader
from django.utils.translation import ugettext_lazy as _
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import *
from rest_framework.views import APIView

from .forms import *
from .models import *
from .utils import *

# Create your views here.

# PLAN

# Datatable Class Plan
class PlanDatatable(Datatable):
    actions = columns.DisplayColumn(_('Actions'), processor='get_actions')

    class Meta:
        model = Plan
        columns = [
            'actions',
            'name',
            'description',
            'monthly_price',
            'yearly_price',
        ]
        search_fields = [
            'name',
            'description',
            'monthly_price',
            'yearly_price',
        ]
        structure_template = "datatableview/bootstrap_structure.html"
        ordering = ['-id']

    @staticmethod
    def get_actions(instance, view, *args, **kwargs):
        rid = int(instance.pk)
        detail_url = reverse('plan_details', args=[rid])
        update_url = reverse('plan_update', args=[rid])
        delete_url = reverse('plan_delete', args=[rid])
        return """
                      <div class="container">
                          <div class="row">
                              <div class="col" style="width: 80px; ">
                                  <a href="{}" class="btn btn-info btn-circle">
                                      <i class="fas fa-eye"></i>
                                  </a>
                              </div>
                              <div class="col" style="width: 80px; ">
                                  <a href="{}" class="btn btn-info btn-circle">
                                      <i class="fas fa-pencil-alt"></i>
                                  </a>
                              </div>
                              <div class="col" style="width: 80px; ">
                                  <a href="{}" class="btn btn-info btn-circle">
                                      <i class="fas fa-trash"></i>
                                  </a>
                              </div>
                          </div>
                      </div>
                      """.format(detail_url, update_url, delete_url)


# Vista DatatableView de Planes
class PlanDatatableView(LoginRequiredMixin, DatatableView):
    model = Plan
    datatable_class = PlanDatatable
    template_name = 'plan/plan_list.html'


# Vista Detalles de Planes
class PlanDetailsView(LoginRequiredMixin, DetailView):
    model = Plan
    template_name = 'plan/plan_detail.html'
    context_object_name = 'plan'


# Vista Actualizacion de Item
class PlanUpdateView(LoginRequiredMixin, UpdateView):
    model = Plan
    template_name = 'plan/plan_update.html'
    form_class = PlanForm
    context_object_name = 'plan'

    def form_invalid(self, form):
        print("Intento de actualizacion de Item fallido")
        error = form.errors
        print(error)
        return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):
        return reverse('plan_list')


# Vista Eliminacion de Item
class PlanDeleteView(LoginRequiredMixin, DeleteView):
    model = Plan
    template_name = 'plan/plan_delete.html'
    context_object_name = 'plan'

    def post(self, request, *args, **kwargs):
        plan_id = kwargs['pk']
        plan = get_object_or_404(Plan, pk=plan_id)
        plan.delete()
        messages.success(self.request, "El registro fue eliminado de forma satisfactoria.")
        return HttpResponseRedirect(reverse('plan_list'))


# Vista Creacion de Item
class PlanCreateView(LoginRequiredMixin, CreateView):
    model = Plan
    form_class = PlanForm
    template_name = 'plan/plan_create.html'

    def get_context_data(self, **kwargs):
        context = super(PlanCreateView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        item = form.save()
        return HttpResponseRedirect(reverse('plan_list'))

    def get_success_url(self):
        return reverse('plan_list')


# PAYMENT HISTORY


# Datatable Class Payment History
class PaymentHistoryDatatable(Datatable):
    actions = columns.DisplayColumn(_('Actions'), processor='get_actions')

    class Meta:
        model = PaymentHistory
        columns = [
            'actions',
            'id',
            'payment_type',
            'date',
            'amount',
            'ref_number',
        ]
        search_fields = [
            'payment_type',
            'date',
            'amount',
            'ref_number',
        ]
        structure_template = "datatableview/bootstrap_structure.html"
        ordering = ['-id']

    @staticmethod
    def get_actions(instance, view, *args, **kwargs):
        rid = int(instance.pk)
        detail_url = reverse('payment_history_details', args=[rid])
        update_url = reverse('payment_history_update', args=[rid])
        delete_url = reverse('payment_history_delete', args=[rid])
        return """
                      <div class="container">
                          <div class="row">
                              <div class="col" style="width: 80px; ">
                                  <a href="{}" class="btn btn-info btn-circle">
                                      <i class="fas fa-eye"></i>
                                  </a>
                              </div>
                              <div class="col" style="width: 80px; ">
                                  <a href="{}" class="btn btn-info btn-circle">
                                      <i class="fas fa-pencil-alt"></i>
                                  </a>
                              </div>
                              <div class="col" style="width: 80px; ">
                                  <a href="{}" class="btn btn-info btn-circle">
                                      <i class="fas fa-trash"></i>
                                  </a>
                              </div>
                          </div>
                      </div>
                      """.format(detail_url, update_url, delete_url)


# Vista DatatableView de PaymentHistory
class PaymentHistoryDatatableView(LoginRequiredMixin, DatatableView):
    model = PaymentHistory
    datatable_class = PaymentHistoryDatatable
    template_name = 'paymentHistory/payment_history_list.html'


# Vista Detalles de PaymentHistory
class PaymentHistoryDetailsView(LoginRequiredMixin, DetailView):
    model = PaymentHistory
    template_name = 'paymentHistory/payment_history_detail.html'
    context_object_name = 'payment_history'


# Vista Actualizacion de PaymentHistory
class PaymentHistoryUpdateView(LoginRequiredMixin, UpdateView):
    model = PaymentHistory
    template_name = 'paymentHistory/payment_history_update.html'
    form_class = PaymentHistoryForm
    context_object_name = 'payment_history'

    def form_invalid(self, form):
        print("Intento de actualizacion de registro fallido")
        error = form.errors
        print(error)
        return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):
        return reverse('payment_history_list')


# Vista Eliminacion de PaymentHistory
class PaymentHistoryDeleteView(LoginRequiredMixin, DeleteView):
    model = PaymentHistory
    template_name = 'paymentHistory/payment_history_delete.html'
    context_object_name = 'payment_history'

    def post(self, request, *args, **kwargs):
        payment_history_id = kwargs['pk']
        payment_history = get_object_or_404(PaymentHistory, pk=payment_history_id)
        payment_history.delete()
        messages.success(self.request, "El registro fue eliminado de forma satisfactoria.")
        return HttpResponseRedirect(reverse('payment_history_list'))


# Vista Creacion de PaymentHistory
class PaymentHistoryCreateView(LoginRequiredMixin, CreateView):
    model = PaymentHistory
    form_class = PaymentHistoryForm
    template_name = 'paymentHistory/payment_history_create.html'

    def get_context_data(self, **kwargs):
        context = super(PaymentHistoryCreateView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        payment = form.save()
        debt = payment.subscription
        try:
            subscription = get_object_or_404(Subscription, pk=debt.id)
            subscription.cancelsubscription()
            payment.save()
            return HttpResponseRedirect(reverse('payment_history_list'))
        except:
            return self.render_to_response(self.get_context_data(form=form))


    def get_success_url(self):
        return reverse('payment_history_list ')


# SUBSCRIPTIONS


# Datatable Class Subscriptions
class SubscriptionsDatatable(Datatable):
    actions = columns.DisplayColumn(_('Actions'), processor='get_actions')

    class Meta:
        model = Subscription
        columns = [
            'actions',
            'chaplain',
            'plan',
            'startDate',
            'endDate',
            'finishDate',
            'isActive',
        ]
        search_fields = [
            'chaplain',
            'plan',
            'startDate',
            'endDate',
            'finishDate',
            'isActive',
        ]
        structure_template = "datatableview/bootstrap_structure.html"
        ordering = ['-id']

    @staticmethod
    def get_actions(instance, view, *args, **kwargs):

pagos/templates/subscriptions/subscriptions_create.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load crispy_forms_field %}
{% block heading %}
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">
        <a href="{% url "subscriptions_list" %}">Suscripciones</a>
    </h1>
{% endblock %}
{% block content %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Crear Suscripcion</h6>
        </div>
        <div class="card-body">
            <form id="id_create_chaplain_form" method="post" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                {{ form.management_form }}
                {{ form.chaplain|as_crispy_field }}
                {{ form.plan|as_crispy_field }}
                {{ form.startDate|as_crispy_field }}
                {{ form.endDate|as_crispy_field }}
                {{ form.finishDate|as_crispy_field }}
                {{ form.isActive|as_crispy_field }}
                <input type="submit" class="btn btn-sm btn-primary shadow-sm" value="Guardar">
                <a class="btn btn-sm btn-light shadow-sm" href="{% url 'subscriptions_list' %}">Cancelar</a>
            </form>
        </div>
    </div>
{% endblock %}

{% block extra_css %}
    <link href="{% static 'build/vendor/chosen-js/chosen.min.css' %}" rel="stylesheet">
    <link href="{% static 'build/vendor/jquery-datetimepicker/jquery.datetimepicker.min.css' %}" rel="stylesheet">
    <link href="{% static 'build/vendor/jquery-ui-dist/jquery-ui.min.css' %}" rel="stylesheet">
    <link href="{% static 'build/vendor/dropify/css/dropify.min.css' %}" rel="stylesheet">
{% endblock %}

{% block extra_js %}
    <script src="{% static 'build/vendor/chosen-js/chosen.jquery.min.js' %}"></script>
    <script src="{% static 'build/vendor/moment/moment.js' %}"></script>
    <script src="{% static 'build/vendor/jquery-datetimepicker/jquery.datetimepicker.full.min.js' %}"></script>
    <script src="{% static 'build/vendor/jquery-mask-plugin/jquery.mask.min.js' %}"></script>
    <script src="{% static 'build/vendor/jquery-formset/jquery.formset.js' %}"></script>
    <script src="{% static 'build/vendor/jquery-ui-dist/jquery-ui.min.js' %}"></script>
    <script src="{% static 'build/vendor/dropify/js/dropify.min.js' %}"></script>
    <script src="{% static 'pagos/js/subscriptions.js' %}"></script>

    <script type="text/javascript">
        $(function () {
            initializeInputs();
        });

    </script>


{% endblock %}

pagos/templates/subscriptions/subscriptions_delete.html
{% extends "layout.html" %}
{% load static %}
{% block heading %}
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">
    <a href="{% url 'subscriptions_list' %}">Suscripciones</a>
  </h1>
{% endblock %}
{% block content %}
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Eliminar Registro de Suscripcion</h6>
    </div>
    <div class="card-body">
      <p>Está Seguro que quiere eliminar este registro? </p>
      <span><b>{{ subscription.chaplain.name}} - {{ chaplain.plan.name }}</b></span>
      <br><br>
      <form method="post" enctype="multipart/form-data" action="{% url 'subscriptions_delete' subscription.id %}">
        {% csrf_token %}
        <input type="submit" class="btn btn-sm btn-primary shadow-sm" value="Confirmar">
        <a class="btn btn-sm btn-light shadow-sm" href="{% url 'subscriptions_list' %}">Volver a Lista de Suscripciones</a>
      </form>
    </div>
  </div>
{% endblock %}

pagos/templates/subscriptions/subscriptions_detail.html
{% extends "layout.html" %}
{% load humanize %}
{% load static %}
{% block heading %}
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">
        <a href="{% url 'subscriptions_list' %}">Suscripciones</a>
    </h1>

{% endblock %}
{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Detalles de Suscripcion ID: {{ subscription.id }}</h6>
        </div>
        <div class="card-body">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <br>
                        <h2 class="text-2xl font-semibold">{{ subscription.chaplain.name }} {{ subscription.chaplain.last_name }}</h2>
                        {#            <p><strong class="text-primary">Nombre de Capellan: </strong> {{ subscription.chaplain.name }}</p>#}
                        <p><strong class="text-primary">Membresia: </strong> {{ subscription.plan.name }} </p>
                        <p><strong class="text-primary">Monto
                            mensual: </strong> {{ subscription.plan.monthly_price|intcomma }} </p>
                        <p><strong class="text-primary">Fecha de
                            Inicio: </strong> {{ subscription.startDate |date:'d/m/Y' }}</p>
                        <p><strong class="text-primary">Fecha de
                            Fin: </strong> {{ subscription.endDate|date:'d/m/Y'|default_if_none:"---" }}</p>
                        <p><strong class="text-primary">Fecha de
                            Finalizacion: </strong> {{ subscription.finishDate|date:'d/m/Y'|default_if_none:"---" }}</p>
                        {% if subscription.isActive == True %}
                            <p><strong class="text-primary">Pagado: No.</strong></p>
                            <p><strong class="text-primary">Link para Pago:</strong><a
                                    href=" {{ subscription.url }} ">
                                 {{ subscription.url }} </a></p>
                            </div>
                            <div class="col">
                                <img src="{{ subscription.url}}/qr"
                                     alt="No QR Image.">
                            </div>
                            </div>
                            </div>

                        {% else %}
                            </div>
                            <div class="col">
                                <br/><br/>
                                <p><strong class="text-primary">Detalles de Pago.</strong></p>
                                {% if subscription.payment.all %}
                                    {% for detail in subscription.payment.all %}
                                        <p><strong class="text-primary">Tipo de pago: </strong> {{ detail.get_payment_type_display }} </p>
                                        <p><strong class="text-primary">Fecha: </strong> {{ detail.date }} </p>
                                        <p><strong class="text-primary">Monto: </strong> {{ detail.amount }} </p>
                                        <p><strong class="text-primary">Numero de referencia: </strong> {{ detail.ref_number }} </p>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            </div>
                        {% endif %}

    <a href="{% url 'subscriptions_update' subscription.id %}" class="btn btn-primary btn-icon-split">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-pencil-alt"></i>
                                        </span>
        <span class="text">Editar</span>
    </a>
    <a href="{% url 'subscriptions_list' %}" class="btn btn-light btn-icon-split">
            <span class="icon text-gray-600">
                <i class="fas fa-arrow-right"></i>
            </span>
        <span class="text">Volver al Listado</span>
    </a>
    </div>
    </div>
{% endblock %}

pagos/templates/subscriptions/subscriptions_list.html
{% extends 'layout.html' %}
{% load static %}

{% block heading %}
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">
    Suscripciones
  </h1>
  <!--<p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
    For more information about DataTables, please visit the <a target="_blank"
                                                               href="https://datatables.net">official DataTables
      documentation</a>.</p>-->

{% endblock %}
{% block content %}
<!-- DataTables Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Suscripciones <a href="{% url 'subscriptions_create' %}" class="btn btn-info btn-circle">
        <i class="fas fa-plus"></i></a>
      </h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        {{ datatable }}
      </div>
    </div>
  </div>
{% endblock %}

{% block extra_css %}
  <!-- Custom styles for this page -->
  <link href="{% static 'build/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

{% endblock %}

{% block extra_js %}
  <!-- Page level plugins -->
  <script src="{% static 'build/vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'build/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'base/js/datatables/numeric-comma.js' %}"></script>
  <script type="text/javascript" charset="utf8" src="{% static 'pagos/js/datatableview.js' %}"></script>

  <!-- Page level custom scripts -->
  <script type="text/javascript">
    $(function (){

        /* se inicializa el datatables */
        datatableview.initialize($('.datatable'),
            /* Archivo de traducción */
            {
                language: {
                    url: "{% url 'datatables_translation' %}",
                },

                /*columnDefs: [
                    { type: "numeric-comma", targets: [8] },
                    {
                        render: $.fn.dataTable.render.number('.', ',', 1, '', ''),
                        targets: 8
                    },
                ],*/
            }
        );
    });

  </script>
{% endblock %}

pagos/templates/subscriptions/subscriptions_update.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load crispy_forms_field %}
{% block heading %}
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">
        <a href="{% url "subscriptions_list" %}">Suscripciones</a>
    </h1>
{% endblock %}
{% block content %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Crear Suscripcion</h6>
        </div>
        <div class="card-body">
            <form id="id_create_chaplain_form" method="post" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                {{ form.management_form }}
                {{ form.chaplain|as_crispy_field }}
                {{ form.plan|as_crispy_field }}
                {{ form.startDate|as_crispy_field }}
                {{ form.endDate|as_crispy_field }}
                {{ form.finishDate|as_crispy_field }}
                {{ form.isActive|as_crispy_field }}
                <input type="submit" class="btn btn-sm btn-primary shadow-sm" value="Guardar">
                <a class="btn btn-sm btn-light shadow-sm" href="{% url 'subscriptions_list' %}">Cancelar</a>
            </form>
        </div>
    </div>
{% endblock %}

{% block extra_css %}
    <link href="{% static 'build/vendor/chosen-js/chosen.min.css' %}" rel="stylesheet">
    <link href="{% static 'build/vendor/jquery-datetimepicker/jquery.datetimepicker.min.css' %}" rel="stylesheet">
    <link href="{% static 'build/vendor/jquery-ui-dist/jquery-ui.min.css' %}" rel="stylesheet">
    <link href="{% static 'build/vendor/dropify/css/dropify.min.css' %}" rel="stylesheet">
{% endblock %}

{% block extra_js %}
    <script src="{% static 'build/vendor/chosen-js/chosen.jquery.min.js' %}"></script>
    <script src="{% static 'build/vendor/moment/moment.js' %}"></script>
    <script src="{% static 'build/vendor/jquery-datetimepicker/jquery.datetimepicker.full.min.js' %}"></script>
    <script src="{% static 'build/vendor/jquery-mask-plugin/jquery.mask.min.js' %}"></script>
    <script src="{% static 'build/vendor/jquery-formset/jquery.formset.js' %}"></script>
    <script src="{% static 'build/vendor/jquery-ui-dist/jquery-ui.min.js' %}"></script>
    <script src="{% static 'build/vendor/dropify/js/dropify.min.js' %}"></script>
    <script src="{% static 'pagos/js/subscriptions.js' %}"></script>

    <script type="text/javascript">
        $(function () {
            initializeInputs();
        });

    </script>


{% endblock %}