acnep/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from acnep import settings

admin.site.site_header = "Sistema ACNEP Admin"
admin.site.site_title = "Sistema ACNEP Portal"
admin.site.index_title = "Bienvenido al administrador del Sistema ACNEP"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'acnep.views.handler404'
handler500 = 'acnep.views.handler500'

base/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

import chaplains
from chaplains import urls

import pagos
from pagos import urls

from .views import *

urlpatterns = [

    # BASE URLs
    path('login', Login.as_view(), name='login' ),
    path('', DashboardView.as_view(), name='dashboard'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('index', BlankView.as_view(), name='index'),

    # Datatables translation
    path('datatables_translation', DataTablesTranslationsJsonView.as_view(), name='datatables_translation'),

    # APPS URLS
    # Chaplains
    path('chaplains/', include(chaplains.urls)),
    # Payment History, Subscriptions and Plans
    # path('', include(pagos.urls)),
]

chaplains/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    path('list/', ChaplainsDatatableView.as_view(), name='chaplain_list'),
    path('details/<int:pk>', ChaplainDetailsView.as_view(), name='chaplain_detail'),
    path('create/', ChaplainCreationView.as_view(), name='chaplain_create'),
    path('update/<int:pk>', ChaplainUpdateView.as_view(), name='chaplain_update'),
    path('delete/<int:pk>', ChaplainDeleteView.as_view(), name='chaplain_delete'),
    path('card/<int:pk>', ChaplainCardView.as_view(), name='chaplain_card'),
]

base/models.py
from datetime import date
from django.db import models
from auditlog.registry import auditlog
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from softdelete.models import SoftDeleteObject


# Create your models here.
class TimeStampModel(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Created at')
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_('Updated at')
    )

    class Meta:
        abstract = True


# PERSON
class Person(TimeStampModel, SoftDeleteObject):
    CITYS = (
        (1, "ASUNCION"),
        (2, "FUERTE OLIMPO"),
        (3, "LA VICTORIA"),
        (4, "MCAL ESTIGARRIBIA"),
        (5, "FILADELFIA"),
        (6, "LOMA PLATA"),
        (7, "JOSE FALCON"),
        (8, "NANAWA"),
        (9, "VILLA HAYES"),
        (10, "BENJAMIN ACEVAL"),
        (11, "PINASCO"),
        (12, "CORPUS CHRISTI"),
        (13, "CURUGUATY"),
        (14, "FRANCISCO CABALLERO A"),
        (15, "ITANARA"),
        (16, "KATUETE"),
        (17, "LA PALOMA"),
        (18, "NUEVA ESPERANZA"),
        (19, "SALTOS DEL GUAIRA"),
        (20, "YGATIMI"),
        (21, "YPEJHU"),
        (22, "PEDRO J CABALLERO"),
        (23, "CAPITAN BADO"),
        (24, "BELLA VISTA NORTE"),
        (25, "ALBERDI"),
        (26, "CERRITO"),
        (27, "DESMOCHADOS"),
        (28, "GRAL DIAZ"),
        (29, "GUAZU CUA"),
        (30, "HUMAITA"),
        (31, "ISLA UMBU"),
        (32, "LAURELES"),
        (33, "MAYOR MARTINEZ"),
        (34, "PASO DE PATRIA"),
        (35, "PILAR"),
        (36, "SAN JUAN NEEMBUCU"),
        (37, "TACUARAS"),
        (38, "VILLA FRANCA"),
        (39, "VILLA OLIVA"),
        (40, "VILLALBIN"),
        (41, "AREGUA"),
        (42, "CAPIATA"),
        (43, "FERNANDO DE LA MORA"),
        (44, "GUARAMBARE"),
        (45, "ITA"),
        (46, "ITAUGUA"),
        (47, "J A SALDIVAR"),
        (48, "LAMBARE"),
        (49, "LIMPIO"),
        (50, "LUQUE"),
        (51, "MARIANO R ALONSO"),
        (52, "NUEVA ITALIA"),
        (53, "NEMBY"),
        (54, "SAN ANTONIO"),
        (55, "SAN LORENZO"),
        (56, "VILLA ELISA"),
        (57, "VILLETA"),
        (58, "YPACARAI"),
        (59, "YPANE"),
        (60, "LOS CEDRALES"),
        (61, "CIUDAD DEL ESTE"),
        (62, "DOMINGO M IRALA"),
        (63, "HERNANDARIAS"),
        (64, "IRUNA"),
        (65, "ITAKYRY"),
        (66, "MBARACAYU"),
        (67, "MINGA GUAZU"),
        (68, "MINGA PORA"),
        (69, "NARANJAL"),
        (70, "NACUNDAY"),
        (71, "JUAN E OLEARY"),
        (72, "PTE FRANCO"),
        (73, "SAN ALBERTO"),
        (74, "SAN CRISTOBAL"),
        (75, "SANTA RITA"),
        (76, "SANTA ROSA MONDAY"),
        (77, "YGUAZU"),
        (78, "ACAHAY"),
        (79, "CAAPUCU"),
        (80, "CABALLERO"),
        (81, "CARAPEGUA"),
        (82, "ESCOBAR"),
        (83, "LA COLMENA"),
        (84, "MBUYAPEY"),
        (85, "PARAGUARI"),
        (86, "PIRAYU"),
        (87, "QUIINDY"),
        (88, "QUYQUYHO"),
        (89, "ROQUE GONZALEZ"),
        (90, "SAPUCAI"),
        (91, "TEBICUARYMI"),
        (92, "YAGUARON"),
        (93, "YBYCUI"),
        (94, "YBYTYMI"),
        (95, "VILLA FLORIDA"),
        (96, "SAN MIGUEL"),
        (97, "SAN JUAN BAUTISTA"),
        (98, "SANTA MARIA"),
        (99, "SAN IGNACIO"),
        (100, "SANTA ROSA MISIONES"),
        (101, "SAN PATRICIO"),
        (102, "SANTIAGO"),
        (103, "AYOLAS"),
        (104, "YABEBYRY"),
        (105, "ALTO VERA"),
        (106, "BELLA VISTA SUR"),
        (107, "CAMBYRETA"),
        (108, "CAPITAN MEZA"),
        (109, "CAPITAN MIRANDA"),
        (110, "CARLOS A LOPEZ"),
        (111, "CARMEN PARANA"),
        (112, "CNEL BOGADO"),
        (113, "EDELIRA"),
        (114, "ENCARNACION"),
        (115, "FRAM"),
        (116, "ARTIGAS"),
        (117, "GRAL DELGADO"),
        (118, "HOHENAU"),
        (119, "ITAPUA POTY"),
        (120, "JESUS"),
        (121, "LA PAZ"),
        (122, "LEANDRO OVIEDO"),
        (123, "NATALIO"),
        (124, "NUEVA ALBORADA"),
        (125, "OBLIGADO"),
        (126, "MAYOR OTANO"),
        (127, "PIRAPO"),
        (128, "SAN COSME Y DAMIAN"),
        (129, "SAN JUAN PARANA"),
        (130, "SAN PEDRO PARANA"),
        (131, "SAN RAFAEL DEL PARANA"),
        (132, "TOMAS ROMERO PEREIRA"),
        (133, "TRINIDAD"),
        (134, "YATYTAY"),
        (135, "ABAI"),
        (136, "BERTONI"),
        (137, "BUENA VISTA"),
        (138, "CAAZAPA"),
        (139, "MACIEL"),
        (140, "GRAL MORINIGO"),
        (141, "SAN JUAN NEPOMUCENO"),
        (142, "TAVAI"),
        (143, "YEGROS"),
        (144, "YUTY"),
        (145, "3 DE FEBRERO"),
        (146, "CAAGUAZU"),
        (147, "CARAYAO"),
        (148, "CECILIO BAEZ"),
        (149, "CNEL OVIEDO"),
        (150, "JOSE D OCAMPOS"),
        (151, "J E ESTIGARRIBIA"),
        (152, "JUAN M FRUTOS"),
        (153, "LA PASTORA"),
        (154, "MCAL LOPEZ"),
        (155, "NUEVA LONDRES"),
        (156, "RI3 CORRALES"),
        (157, "RAUL A OVIEDO"),
        (158, "REPATRIACION"),
        (159, "SAN JOAQUIN"),
        (160, "SAN JOSE ARROYOS"),
        (161, "SIMON BOLIVAR"),
        (162, "SANTA ROSA MBUTUY"),
        (163, "VAQUERIA"),
        (164, "YHU"),
        (165, "BORJA"),
        (166, "DR BOTRELL"),
        (167, "CNEL MARTINEZ"),
        (168, "COL INDEPENDENCIA"),
        (169, "FELIX PEREZ CARDOZO"),
        (170, "GRAL GARAY"),
        (171, "ITAPE"),
        (172, "ITURBE"),
        (173, "FASSARDI"),
        (174, "MBOCAYATY"),
        (175, "NATALICIO TALAVERA"),
        (176, "NUMI"),
        (177, "PASO YOBAI"),
        (178, "SAN SALVADOR"),
        (179, "TROCHE"),
        (180, "VILLARRICA"),
        (181, "YATAITY"),
        (182, "ALTOS"),
        (183, "ARROYOS Y ESTEROS"),
        (184, "ATYRA"),
        (185, "CAACUPE"),
        (186, "CARAGUATAY"),
        (187, "EMBOSCADA"),
        (188, "EUSEBIO AYALA"),
        (189, "ISLA PUCU"),
        (190, "ITACURUBI CORDILLERA"),
        (191, "JUAN DE MENA"),
        (192, "LOMA GRANDE"),
        (193, "MBOCAYATY DEL YHAGUY"),
        (194, "NUEVA COLOMBIA"),
        (195, "PIRIBEBUY"),
        (196, "PRIMERO DE MARZO"),
        (197, "SAN BERNARDINO"),
        (198, "SAN JOSE OBRERO"),
        (199, "SANTA ELENA"),
        (200, "TOBATI"),
        (201, "VALENZUELA"),
        (202, "25 DE DICIEMBRE"),
        (203, "ANTEQUERA"),
        (204, "GRAL AQUINO"),
        (205, "CAPIIBARY"),
        (206, "CHORE"),
        (207, "GRAL RESQUIN"),
        (208, "GUAYAIBI"),
        (209, "ITACURUBI ROSARIO"),
        (210, "LIMA"),
        (211, "NUEVA GERMANIA"),
        (212, "SAN ESTANISLAO"),
        (213, "SAN PABLO"),
        (214, "SAN PEDRO YCUAMANDYYU"),
        (215, "SANTA ROSA DEL AGUARAY"),
        (216, "TACUATI"),
        (217, "UNION"),
        (218, "VILLA DEL ROSARIO"),
        (219, "YATAITY DEL NORTE"),
        (220, "SAN LAZARO"),
        (221, "BELEN"),
        (222, "CONCEPCION"),
        (223, "HORQUETA"),
        (224, "LORETO"),
        (225, "SAN CARLOS"),
        (226, "YBY YAU"),
        (227, "JUAN LEON MALLORQUIN"),
        (228, "AZOTE Y"),
        (229, "ZANJA PYTA"),
        (230, "SGTO.JOSE FELIX LOPEZ"),
        (231, "BAHIA NEGRA"),
        (232, "TTE 1 IRALA FERNANDEZ"),
        (233, "TTE.ESTEBAN MARTINEZ"),
        (234, "GRAL.BRUGUEZ"),
        (235, "LIBERACION"),
        (236, "YRYVU CUA"),
        (237, "YASY KAÑY"),
        (238, "YBYRAROBANA"),
        (239, "NUEVA TOLEDO"),
        (240, "TEMBIAPORA"),
        (241, "TEBICUARY"),
        (242, "TAVAPY"),
        (243, "SANTA FE DEL PARANA"),
        (244, "3 DE MAYO"),
        (245, "CARMELO PERALTA"),
        (246, "RAUL PEÑA"),
    )

    name = models.CharField(
        verbose_name=_('Name'),
        max_length=100,
        blank=False, null=False
    )
    last_name = models.CharField(
        verbose_name=_('Last Name'),
        max_length=100,
        blank=False, null=False
    )
    birth_date = models.DateField(
        verbose_name=_('Birth Date'),
        blank=True, null=True,
    )
    MALE_CODE = 0
    FEMALE_CODE = 1

    SEX_CODES = (
        (MALE_CODE, _('Male')),
        (FEMALE_CODE, _('Female')),
        (None, _('Not selected')),
    )
    sex = models.IntegerField(
        verbose_name=_('Sex'),
        choices=SEX_CODES,
        null=True, blank=True,
        default=None
    )
    email = models.EmailField(
        verbose_name=_('Email'),
        blank=True, null=True
    )
    document_number = models.CharField(
        verbose_name=_('Document Number'),
        unique=True,
        max_length=10,
        blank=False, null=False
    )
    address = models.CharField(
        verbose_name=_('Address'),
        max_length=150,
        blank=True, null=True
    )
    city = models.IntegerField(
        verbose_name=_('City'),
        null=True, blank=True,
        choices=CITYS,
        default=1
    )
    phone_number = models.CharField(
        verbose_name=_('Phone Number'),
        max_length=20,
        null=True, blank=True
    )

    class Meta:
        abstract = True

    def full_name(self):
        return self.name + ' ' + self.last_name

    def calculate_age(self):
        born = self.birth_date
        if born:
            today = date.today()
            years = today.year - born.year - ((today.month, today.day) < (born.month, born.day))
            return years
        else:
            return '---'


auditlog.register(Person)

chaplains/models.py
import datetime

from django.db import models
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _
from auditlog.registry import auditlog
from django_countries.fields import CountryField
from django.contrib.auth.models import User
from base.models import Person
# Create your models here.
from softdelete.models import SoftDeleteObject


class Chaplain(Person):
    CIVIL_STATES = (
        (1, "Soltero/a"),
        (2, "Casado/a"),
        (3, "Viudo/a"),
        (4, "Divorciado/a"),
        (5, "Concubino/a"),
        (None, "No seleccionado")
    )
    RANGES = (
        ("Alferes Capellán Superior", "Alferes Capellán Superior"),
        ("Capellán Nacional", "Capellán Nacional"),
        ("Obispo Capellán General", "Obispo Capellán General"),
        ("Obispo Capellán Superior", "Obispo Capellán Superior"),
    )
    civil = models.IntegerField(
        verbose_name=_('Civil State'),
        choices=CIVIL_STATES,
        null=True, blank=True,
        default=None
    )
    country = CountryField(
        verbose_name=_('Nationality'),
        null=True, blank=True
    )
    reference = models.CharField(
        verbose_name=_('Reference'),
        null=True, blank=True,
        max_length=40,
    )
    user = models.ForeignKey(
        to=User,
        verbose_name=_('User'),
        related_name='chaplain',
        null=True, blank=True,
        on_delete=models.PROTECT,
    )
    image = models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')
    range = models.CharField(
        verbose_name=_('Range'),
        max_length=100,
        choices=RANGES,
        blank=True, null=True
    )
    destacamento = models.CharField(verbose_name=_('Destacamento'),
                                    blank=True, null=True,
                                    max_length=100)
    admission_date = models.DateField(verbose_name=_('Admission Date'),
                                      blank=True, null=True )

    class Meta:
        verbose_name = _('Chaplain')
        verbose_name_plural = _('Chaplains')

    def __str__(self):
        return self.name + ' ' + self.last_name


auditlog.register(Chaplain)

chaplains/forms.py
from datetime import datetime
from django import forms
from django.forms import ModelForm
from django_countries.fields import CountryField

from .models import *
from crispy_forms.layout import Layout, Div, Row, Column, Field
from crispy_forms.helper import FormHelper
from django.utils.translation import ugettext_lazy as _

# Chaplain Form


class ChaplainForm(ModelForm):
    country = CountryField().formfield(blank=True, blank_label=_('Choose Country'), required=False)
    name = forms.CharField(label=_('Name'))
    last_name = forms.CharField(label=_('Last Name'))
    birth_date = forms.DateField(
        required=False,
        label=_('Birth Date'),
        widget=forms.DateInput(format='%d/%m/%Y', attrs={'placeholder': 'dd/mm/aaaa'})
    )
    sex = forms.ChoiceField(
        widget=forms.Select,
        choices=Chaplain.SEX_CODES,
        required=False
    )
    email = forms.EmailField(label=_('Email'), required=False)
    document_number = forms.CharField(label=_('Document Number'))
    address = forms.CharField(label=_('Address'), required=False)
    city = forms.ChoiceField(
        widget=forms.Select,
        choices=Chaplain.CITYS,
        required=False
    )
    phone_number = forms.CharField(label=_('Phone Number'),required=False)
    civil = forms.ChoiceField(
        widget=forms.Select,
        choices=Chaplain.CIVIL_STATES,
        required=False,
    )
    reference = forms.CharField(label=_('Reference'), required=False)
    image = forms.ImageField(required=False)
    destacamento = forms.CharField(label=_('Destacamento'), required=False)
    admission_date = forms.DateField(
        required=True,
        label=_('Admission Date'),
        widget=forms.DateInput(format='%d/%m/%Y', attrs={'placeholder': 'dd/mm/aaaa'})
    )
    range = forms.ChoiceField(
        widget=forms.Select,
        choices=Chaplain.RANGES,
        required=True
    )
    class Meta:
        model = Chaplain
        fields = [
            'name',
            'last_name',
            'birth_date',
            'sex',
            'email',
            'document_number',
            'address',
            'city',
            'phone_number',
            'civil',
            'country',
            'reference',
            'image',
            'range',
            'destacamento',
            'admission_date'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['birth_date'].input_formats = ['%d/%m/%Y']
        self.fields['admission_date'].input_formats = ['%d/%m/%Y']

chaplains/templates/chaplains/chaplain_card.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Card</title>
</head>
<body class="">
    <div class="card" style="width: 340px; height: 200px;">
        <div class="card-body" style="margin: 0; padding: 8px;">
            <div class="d-flex gap-3">
                <img src="{% static 'chaplains/img/logo.svg' %}" alt="logo" style="width: 50px; height: 50px;">
                
                <div class="d-flex flex-column" style="width: 200px;">
                    <p style="font-size: 8px; color: #375da0; margin: 0;">República del Paraguay</p>
                    <p style="font-size: 10px; color: #477bd4; margin: 0;">Asociación de Capellanes Nacionales Evangélicos del Paraguay</p>
                    <p style="font-size: 8px; color: #375da0; margin: 0;">Capellanía Nacional Evangélica</p>
                    <p style="font-size: 8px; color: #375da0; margin: 0;">Decreto N 1244/19</p>
                </div>
            </div>
        </div>
        <div class="d-flex p-1 m-1" style="margin: 0;">
            <div class="d-flex flex-column">
                <div class="card me-2" style="width: 70px; height: 70px;">
                    <img src="" alt="No foto" style="width: 100%; height: 100%;">
                </div>
                <p style="font-size: 12px; margin: 0; font-weight: bold; margin: 5px;">{{ chaplain.document_number }}</p>
            </div>
            <div style="margin: -14px 10px; width: 130px; overflow: hidden;">
                <p style="font-size: 10px; margin: 0; font-weight: bold;">{{ chaplain.name }} {{ chaplain.last_name }}</p>
                <p style="font-size: 9px; margin: 0;">Nombre </p>

                <p style="font-size: 10px; margin: 0; font-weight: bold;">{{ chaplain.range }}</p>
                <p style="font-size: 9px; margin: 0;">Grado</p>

                <p style="font-size: 10px; margin: 0; font-weight: bold;">{{ chaplain.country }}</p>
                <p style="font-size: 9px; margin: 0;">Nacionalidad</p>

                <p style="font-size: 10px; margin: 0; font-weight: bold;">{{ chaplain.admission_date }}</p>
                <p style="font-size: 9px; margin: 0;">Fecha de Expedición</p>
            </div>
            <div class="card" style="width: 80px; height: 80px; margin-left: 0px;">
                <img src="{% static 'chaplains/img/img.png' %}" alt="No existe foto">
            </div>
        </div>
    </div>

    <div class="card mt-2 p-3" style="width: 340px; height: 200px;">
        <div>
            <p style="font-size: 8px; margin: 0;"><b>CONSTITUCIÓN NACIONAL ART.24 “GARANTÍAS CONSTITUCIONALES”</b></p>
            <p style="font-size: 8px; margin: 0;"><b>Registro Nacional de Pastores Capellanes Evangélicos</b></p>
            <p style="font-size: 8px; margin: 0;">Registrado por el Poder Judicial N 500/14 460 en fecha 05/09/2000</p>
            <p style="font-size: 8px; margin: 0; padding-bottom: 5px;">Decreto N 14.376/001 y el Vice-Ministro de Culto.</p>

            <p style="font-size: 8px; margin: 0; padding-bottom: 5px;">El Obispo Capellán Presidente de <b>ACNEP</b> hace constar que la fotografía y las documentaciones pertenecen al Capellán Evangelico. Y que este carnet solamente es válido para fines de su Ministerio.</p>

            <p style="font-size: 8px; margin: 0; padding-bottom: 5px;">Solicita a las <b>autoridades Civiles, Militares y Policiales,</b> le preste la cooperación que le sean requeridas para el mejor cumplimiento del  Ministerio.</p>
        </div>
        <div class="d-flex">
            <div>
                <p style="font-size: 10px; margin: 0; color: red;">Caso de Urgencia Llamar</p>
                <p style="font-size: 10px; margin: 0; color: red;">0985 874 195 - San Lorenzo, Paraguay</p>
            </div>
            <div>
                <div style="margin-left: 30px;">
                    <div class="card" style="width: 100px; height: 30px;">

                    </div>
                    <div class="d-flex flex-column align-items-center">
                        <p style="font-size: 8px; margin: 0;">Carlos Miguel Alfaro</p>
                        <p style="font-size: 8px; margin: 0;">Obispo Capellan Presidente</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

chaplains/templates/chaplains/chaplains_delete.html
{% extends "layout.html" %}
{% load static %}
{% block heading %}
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">
    <a href="{% url 'chaplain_list' %}">Capellanes</a>
  </h1>
{% endblock %}
{% block content %}
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Eliminar Capellan</h6>
    </div>
    <div class="card-body">
      <p>Está Seguro que quiere eliminar este registro? </p>
      <span><b>{{ chaplain.name}} {{ chaplain.last_name }}</b></span>
      <br><br>
      <form method="post" enctype="multipart/form-data" action="{% url 'chaplain_delete' chaplain.id %}">
        {% csrf_token %}
        <input type="submit" class="btn btn-sm btn-primary shadow-sm" value="Confirmar">
        <a class="btn btn-sm btn-light shadow-sm" href="{% url 'chaplain_list' %}">Volver a Lista de Capellanes</a>
      </form>
    </div>
  </div>
{% endblock %}

chaplains/templates/chaplains/chaplains_detail.html
{% extends "layout.html" %}
{% load static %}
{% load humanize %}
{% block heading %}
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">
        <a href="{% url 'chaplain_list' %}">Capellanes</a>
    </h1>

{% endblock %}
{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Detalles de capellan ID: {{ chaplain.id }}</h6>
        </div>
        <div class="card-body">
            <h2 class="text-2xl font-semibold">{{ chaplain.name }} {{ chaplain.last_name }}</h2>
            {% if chaplain.image %}
            <img src="{{ chaplain.image.url}}" alt="Placeholder image" style="max-width: 250px; max-height: 250px;"/>
            {% endif %}
            <p><strong class="text-primary">N&deg; de Documento: </strong> {{ chaplain.document_number | intcomma}}</p>
            <p><strong class="text-primary">Fecha Nac.: </strong> {{ chaplain.birth_date|date:'d/m/Y' }} ({{ chaplain.calculate_age }}
                años)</p>
            <p><strong class="text-primary">Estado Civil: </strong> {{ chaplain.get_civil_display }}</p>
            <p><strong class="text-primary">Sexo: </strong> {{ chaplain.get_sex_display }}</p>
            <p><strong class="text-primary">Email: </strong> {{ chaplain.email|default_if_none:"---" }}</p>
            <p><strong class="text-primary">Tel&eacute;fono: </strong> {{ chaplain.phone_number }}</p>
            <p><strong class="text-primary">Nacionalidad: </strong> {{ chaplain.country.name }}</p>
            <p><strong class="text-primary">Ciudad: </strong> {{ chaplain.get_city_display|default_if_none:"---" }}</p>
            <p><strong class="text-primary">Direcci&oacute;n: </strong> {{ chaplain.address|default_if_none:"---" }}</p>
            <p><strong class="text-primary">Reference: </strong> {{ chaplain.reference|default_if_none:"" }}</p>

            <a href="{% url 'chaplain_update' chaplain.id %}" class="btn btn-primary btn-icon-split">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-pencil-alt"></i>
                                        </span>
                <span class="text">Editar</span>
            </a>
        {% if user.is_staff %}
            <a href="{% url 'chaplain_list' %}" class="btn btn-light btn-icon-split">
            <span class="icon text-gray-600">
                <i class="fas fa-arrow-right"></i>
            </span>
                <span class="text">Volver al Listado</span>
            </a>
        {% endif %}
        </div>
    </div>
{% endblock %}